/*
 * Fastboot command
 *
 * Copyright (c) 2014 Imagination Technologies
 * Author: Chris Larsen <chris.larsen@imgtec.com>
 *
 * Boot an image which is generated by android mkbootimg tool
 *
 * (C) Copyright 2000-2003
 * Wolfgang Denk, DENX Software Engineering, wd@denx.de.
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

/*
 * Misc boot support
 */
#include <common.h>
#include <command.h>
#include <version.h>
#include <net.h>

#ifdef CONFIG_CMD_FASTBOOT

/*
 * This file should have only Fastboot code generic across all
 * platforms.  Other, platform specific files will have the platform
 * specific implementations of fastboot_usb_init(),
 * fastboot_usb_detected(), and fastboot_usb_boot).
 */
int do_fastboot(cmd_tbl_t * cmdtp, int flag, int argc, char *const argv[])
{
	fastboot_usb_init();

	if (fastboot_usb_detected()) {
		fastboot_usb_boot(0, 0, 0);
	} else {
		printf("***** ERROR %s:%d: No USB connection detected\n",
		       __FILE__, __LINE__);
		printf("***** Fastboot terminated\n");
		printf("***** Check USB connection, then retry.\n");
	}

	return 0;
}

U_BOOT_CMD(fastboot, 2, 1, do_fastboot,
	   "use USB Fastboot protocol",
	   "[inactive timeout]\n"
	   "    - Run as a fastboot usb device.\n"
	   "    - The optional inactive timeout is the decimal seconds before\n"
	   "    - the normal console resumes\n");
#endif
